[project]
name = "Decent-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chatterbot>=1.2.6",
    "chatterbot-corpus>=1.2.2",
    "pyyaml>=6.0.2",
    "spacy>=3.8.7",
]
